### ISSUE TITLE
Processor cookiecutter 

### ISSUE THREAD

**Issue by pkcakeout** [comic/evalutils#207]
# Required features
- [x] Loading of images must be automated
- ~~Processor specifications must describe which input formats are expected~~
    - [x] If files are not specified they should be ignored
    - [x] Inputs should support MHD/MHA/TIFF image formats
    - [x] Inputs should support CSV format
- [x] Support for multi-case processing is desirable
- [x] Call a standard function to execute processing
    - Similar to evalutils, this should be generated automatically from the cookiecutter project
- Results:
    - [x] JSON output (as python data structures)
    - Later: Overlays
- [x] Configurable required resources for running the container
    - ~~Automatically switch GPU enabled docker image if req. gpu_count > 0~~
- [x] Dockerfile generation
- [x] Local test run support
- [x] Write tests 
    - [x] processor template generation
    - [x] processor CLI tests
    - [x] processor template runs on dummy data
    - [x] local test / build / export tools works
- [x] Partly updated documentation (needs a more comprehensive guide in the future)

**Comment by silvandeleemput** [comment]
* Setup of continuous integrations builds can be done through the existing Travis CI setup, since we want to integrate the processor templating inside `evalutils`. Tests still need to be written.

* Required resources can now be set through the evalutils CLI and get inserted into the Dockerfile using cookiecutter. See the following list:

    - com.radboudumc.diag.processor.hardware.cpu.count (int +)
    - com.radboudumc.diag.processor.hardware.cpu.capabilities (list of string *)
    - com.radboudumc.diag.processor.hardware.memory (string)
    - com.radboudumc.diag.processor.hardware.gpu.count (int *)
    - com.radboudumc.diag.processor.hardware.gpu.cuda_compute_capability (string)
    - com.radboudumc.diag.processor.hardware.gpu.memory (string)

* Additionally, the following meta data will be required to set:

    - com.radboudumc.diag.processor.author (string)
    - com.radboudumc.diag.processor.ticket (string)
    - com.radboudumc.diag.processor.name (string)

**Comment by silvandeleemput** [comment]
I studied the [EnvoyAI API](https://github.com/EnvoyAI/examples), which do some interesting things:
* Specification of inputs and outputs through (json/yaml) schema in the DockerFile including specific [datatypes](https://github.com/EnvoyAI/examples/blob/master/TYPES.md) for all
    * Input and output file paths are hardcoded.
* Apparently it usually expects to process only a single case / run, but it does support e.g. dicom-series datatypes
* Support for labels in the dockerfile for displaying certain datatypes

**Comment by jmsmkn** [comment]
Looks good!

> * Additionally, the following meta data will be required to set:
>   
>   * com.radboudumc.diag.processor.author (string)
>   * com.radboudumc.diag.processor.ticket (string)
>   * com.radboudumc.diag.processor.name (string)

I wouldn't make these required, or at least have an option to turn this off. We will want to use this library elsewhere, eg, challenges on grand challenge that take in processors from users, rather than prediction files.

**Comment by silvandeleemput** [comment]
@jmsmkn I would opt to keep the `com.radboudumc.diag.processor.name` label, since this will be used by cookiecutter for project folder and class creation (and maybe roughly specify its purpose)

The `author` label might even be unnecessary since a processor/algorithm will be tagged upon upload to grand-challenge.

The `ticket` label is only for internal use and I think prompting might be strange for external users. We could keep it optional for internal use though and maybe let users specify it with a flag. (should be well documented)

**Comment by jmsmkn** [comment]
What is the status of this issue? The PR was merged but there are probably some things left over. Should we continue in a new issue for these?

**Comment by silvandeleemput** [comment]
@jmsmkn I think, the main things left to do are, which are addressed in different issues:
* [ ] Documentation for the processor template #271
* [ ] Adding schemas for input/output formatting and better grand-challenge integration #246

I think this issue can be closed.

**Comment by jmsmkn** [comment]
Continued in #246
