### ISSUE TITLE
How to create evaluation containes for different sub-challenges?

### ISSUE THREAD

**Issue by prash-p** [comic/evalutils#251]
Hi, it wasn't clear to me from the documentation how to use evalutils to evaluate submissions for different sub-datasets within one given challenge. Is it best practice to create different containers for different sub-datasets, and is there some way on the grand-challenges website to assign a specific container for a given sub-evaluation?

**Comment by jmsmkn** [comment]
For most of the challenges there is only 1 dataset and 1 evaluation, and so that is the use case that is supported directly by evalutils. 

Grand challenge only supports 1 active container image per challenge (eg, mychallenge.grand-challenge.org will only be able to use 1 container image). Therefore, you will need to handle any sub-challenge splits yourself within that 1 container image. An alternative is to create multiple challenges, 1 for each sub task, each with its own evaluation.

**Comment by prash-p** [comment]
@jmsmkn Could you provide a little more guidance on how to handle splits in the container? My sub-datasets have a different prefix in the filename for example, so should I extend one of the ClassificationEvaluation methods to do this? Thanks for your time!

**Comment by jmsmkn** [comment]
Treat each sub-task as it's own evaluation and use evalutils to template each one. Then, write an overarching script to call each sub-evaluation with the correct data (passing the correct `ground_truth_path`, `predictions_path` and `output_file` https://evalutils.readthedocs.io/en/latest/modules.html#module-evalutils) and create the aggregated results, writing the aggregate file to `/output/metrics.json`. Call this script from the entrypoint from your container.
