### ISSUE TITLE
Question about the automatic evaluation pipeline when the ground truth of each patient is the folder.

### ISSUE THREAD

**Issue by Luoxd1996** [comic/evalutils#348]
* evalutils version:latest
* Python version:3.10
* Operating System:ubuntu22.04

### Description
I found that in the segmentation [example](https://comic.github.io/evalutils/index.html), the groud-truth just supports each volume has one segmentation file, but in the [SegRap2023](example), each patient has many individual organs files, so each patient ground truth is a folder rather than a single files, like this struct:
├─ SegRap_0001
   ├─ Brain.nii.gz
   ├─ Brainstem.nii.gz
   ├─ ...
├─ ...
   ├─ Brain.nii.gz
   ├─ Brainstem.nii.gz
   ├─ ...
├─ SegRap_xxxx
   ├─ Brain.nii.gz
   ├─ Brainstem.nii.gz
   ├─ ...
I don't know how to modify the segmentation example to suit our task automatic evaluation on the grand challenge, do you give us some advice?
### What I Did
I don't know how to solve it.
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
Ok.

**Comment by jmsmkn** [comment]
Your ground truth folder can be any format as you're only adding this to your docker container image. For example, you could:

- sort your images into one subfolder per patient,
- or keep it flat and add the patient name to each file, 
- or change your ground truth files so that the segmentations are stacked in the 4th dimension,
- or change your ground truth files so that the segmentations are in a single 3D volume (so long as the segmentations are not overlapping).

This is not really an issue with the evalutils library. For help with your challenge setup please contact the Grand Challenge support email and they will be happy to meet to get you setup.
