### ISSUE TITLE
Flakey stats tests

### ISSUE THREAD

**Issue by jmsmkn** [comic/evalutils#65]
Sometimes the tests for the stats module fail, it doesn't seem to be predictable. Some of the tests are using `randint` in parametrize, we should fix this. For instance: https://travis-ci.org/comic/evalutils/builds/430622727 with `PYTHONHASHSEED='3286834659'`. 

cc: @silvandeleemput

**Comment by jmsmkn** [comment]
Also failures with `PYTHONHASHSEED='394'`,  `PYTHONHASHSEED='1215375498'`. 

OK with `PYTHONHASHSEED='53'`

**Comment by silvandeleemput** [comment]
Well I am looking into it right now. Having stress tested the whole stats test by greatly ramping up the number of iterations (500+) I found the following:

It is not caused by the change from distance_transform_edt to distance_transform_edt_float32 and the error only appears to be caused by the test_hd test with a low occurrence rate of approximately 1/125. 

I'll have a closer look at the test tomorrow.

**Comment by silvandeleemput** [comment]
The issue was caused by a discrepancy between the SimpleITK HausdorffDistanceImageFilter and the stats.hausdorff_distance method. The latter has an parameter for connectivity whereas the former only uses a fixed connectivity, hence when the two are at a mismatch differing Hausdorff metrics can occur with a small probability. Having taken out this connectivity setting should fix this issue for me for 1000+ random seeds.
